################################################################################
# Supplementary Figure 6 A
################################################################################
library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)
library(ggplot2)
library(limma)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(MySeuratWrappers)

p1<-VlnPlot(AB, features = c("SLC1A3"),idents = 'NSC/Astrocyte',pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "NSC_Astrocyte_SLC1A3.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("SNAP25"),idents = c('DG_ExN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "DG_ExN_SNAP25.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("SNAP25"),idents = c('nonDG_ExN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "nonDG_ExN_SNAP25.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("SNAP25"),idents = c('ImN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "ImN_SNAP25.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("SNAP25"),idents = c('InN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "InN_SNAP25.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("PROX1"),idents = 'DG_ExN',pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "DG_ExN_PROX1.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("CAMK2A"),idents = c('DG_ExN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "DG_ExN_CAM2A.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("CAMK2A"),idents = c('nonDG_ExN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "nonDG_ExN_CAM2A.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("DCX"),idents = c('ImN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "ImN_DCX.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("DCX"),idents = c('ImN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "ImN_DCX.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("SLC6A1"),idents = c('InN'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "InN_SLC6A1.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("GFAP"),idents = 'NSC/Astrocyte',pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "NSC_Astrocyte_HOPX.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("PTPRC"),idents = 'Microglia',pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "Microglia_PTPRC.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("CSF1R"),idents = 'Microglia',pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "Microglia_CSF1R.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("PDGFRA"),idents = c('OPC'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "OPC_PDGFRA.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("VCAN"),idents = c('OPC'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "OPC_VCAN.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("MOG"),idents = c('MOL'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "MOL_MOG.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("MOG"),idents = c('NFOL'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "NFOL_MOG.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("BCAS1"),idents = c('NFOL'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "NFOL_BCAS1.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("RGS5"),idents = c('End'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "End.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("CFAP54"),idents = c('Ependymal'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "Ependymal_CFAP54.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("DNAH9"),idents = c('Ependymal'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "Ependymal_DNAH9.pdf", plot = p1, device = 'pdf', width = 5, height = 5)
p1<-VlnPlot(AB, features = c("DCN"),idents = c('Pericyte'),pt.size = 0,split.by = "age",ncol = 1)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "Pericyte_DCN.pdf", plot = p1, device = 'pdf', width = 5, height = 5)

################################################################################
# Supplementary Figure 6 H
################################################################################
p1 <- VlnPlot(AB,features = c("IGF1R"),split.by = "age", pt.size=0.01,combine =T)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "DDIT4_1.pdf", plot = p1, device = 'pdf', width = 25, height = 3)
p1 <- VlnPlot(AB,features = c("DDIT4"),split.by = "age", pt.size=0.01,combine =T)+theme(axis.title.x=element_text(size=0,angle=0))
ggsave(filename = "DDIT4_1.pdf", plot = p1, device = 'pdf', width = 25, height = 3)


